# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostify" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/anadinema/ghostify/releases/download/v#{version}/ghostify_darwin_amd64.tar.gz",
        verified: "github.com/anadinema/ghostify"
      sha256 "359a23d7108e503ac98a8516902f14df2c5edea67cf3a8dc3f5ee268763883cf"
    end
    on_arm do
      url "https://github.com/anadinema/ghostify/releases/download/v#{version}/ghostify_darwin_arm64.tar.gz",
        verified: "github.com/anadinema/ghostify"
      sha256 "0d3e2c617d26b0fd448898ec68b4e7339db0d1fb5c515bac4ae984e12b913d59"
    end
  end

  name "ghostify"
  desc "ghostify — wrap on spotify-player with proper macos app integration"
  homepage "https://github.com/anadinema/ghostify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost-spot"
  binary "ghostify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghost-spot"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostify"]
    end
  end

  uninstall_postflight do
    system_command "/usr/bin/rm", args: ["-rf", "~/Applications/Ghostify.app"]
  end

  # No zap stanza required

  caveats <<~EOS
    To complete setup, run one of:
      ghost-spot setup --preset work
      ghost-spot setup --preset personal
      ghost-spot setup --device-name "My Custom Name"

    This creates ~/Applications/Ghostify.app for macOS integration (AltTab, media keys).
    The app bundle is hidden from Spotlight automatically.
  EOS
end
