# This file was generated by GoReleaser. DO NOT EDIT.
cask "yak" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "33fd05d343406787dcb5f759801c1b6d24db19c095813f0d101c79fc50777f19"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "17f0ebea0fa5b72eacf51e36b7601aa4ff91b37f941229e3ed8fa90c8c24f02f"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  on_linux do
    on_intel do
      sha256 "471149024dbc725357688306e8c8d7b90046efecc76191132a66e052576ac023"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "563aebe0e3dddd299a335254ced6c1dab5d981bb68d0e50692a145652b67dead"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  name "yak"
  desc "Yet Another AWS Kit — AWS SSO and credential management"
  homepage "https://yak.anadinema.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yak"
  generate_completions_from_executable "bin/yak", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yak"]
    end
  end

  # No zap stanza required

end
