# This file was generated by GoReleaser. DO NOT EDIT.
cask "yak" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "19013cf327ef73c5c291a9ae2705cb66acea9796ed0c2f876a245de5ad0a7b96"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "49d77b8b2bcf57f7d0fe3583c43b7c97092e1990339fe648e9cac9eceddec6cd"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb59f203e8099b8023d01577058bcd3888e1c168f6e0a2c8bfd1069cd1a92001"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "c58ca8c90ad033d3ff7bf8e3d44fa0d39956ea059a77c5cf35bd54f4a6b7289c"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  name "yak"
  desc "Yet Another AWS Kit — AWS SSO and credential management"
  homepage "https://yak.anadinema.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yak"
  generate_completions_from_executable "bin/yak", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
