# This file was generated by GoReleaser. DO NOT EDIT.
cask "yak" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7526a4c29e6f7eb748d25d6bdfd04c9b072aac69ae758fe978ff19bae3306fc0"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "2801d8b571cf563bacb386927a0fbba64d6763a6cd1711f7bb852d55806d0c42"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_darwin_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  on_linux do
    on_intel do
      sha256 "2aeba390f9e5d19b4ca7f13302c013c71b6420d941dc588cf13ba4a4d8904d63"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_amd64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
    on_arm do
      sha256 "295112720d5a711bd5be915060ad02dbdb68054dbc062dd2e867b5edba74ee96"
      url "https://github.com/anadinema/yak/releases/download/v#{version}/yak_linux_arm64.tar.gz",
        verified: "github.com/anadinema/yak"
    end
  end

  name "yak"
  desc "Yet Another AWS Kit — AWS SSO and credential management"
  homepage "https://yak.anadinema.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yak"
  generate_completions_from_executable "bin/yak", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
